---
title: Elevator.js Quarto Extension
subtitle: "Quarto Extension"
author:
  - name: "Mickaël CANOUIL, _Ph.D._"
    orcid: "0000-0002-3396-4549"
    url: "https://mickael.canouil.fr"
format:
  html:
    output-file: index
    toc: true
---

This extension provides support and shortcode to [Elevator.js](https://github.com/tholman/elevator.js).

Animation is only available for HTML-based documents.

## Installation

```bash
quarto add mcanouil/quarto-elevator@1.3.0
```

This will install the extension under the `_extensions` subdirectory.

If you're using version control, you will want to check in this directory.

## Usage

To add an elevator button, use the `{{{< elevator >}}}` shortcode:

- Mandatory:

  ```markdown
  {{{< elevator >}}}
  ```

- Optional `<text-button>`, `<anchor-target>`, and `<audio=audio.mp3>`:

  ```markdown
  {{{< elevator <text-button> <anchor-target> <audio=audio.mp3> >}}}
  ```

:::: {style='text-align: center;'}

```{=html}
<style>
.down-arrow {
  font-size: 120px;
  margin-top: 120px;
  margin-bottom: 120px;
  text-shadow: 0px -20px #0C1F31, 0px 0px #C33329;
  color: rgba(0,0,0,0);
  -webkit-transform: scaleY(0.8);
  -moz-transform: scaleY(0.8);
  transform: scaleY(0.8);
}
</style>
```

Elevator.js fixes those awkward "scroll to top" moments the old fashioned way.

`<div class="down-arrow">&#9660;</div>`{=html}
First we need to get to the bottom of the page.
`<div class="down-arrow">&#9660;</div>`{=html}
Because you're already at the top.
`<div class="down-arrow">&#9660;</div>`{=html}
So a "back to top" button wouldn't make sense.
`<div class="down-arrow">&#9660;</div>`{=html}
Down down down.
`<div class="down-arrow">&#9660;</div>`{=html}
## Wow, all this scrolling
`<div class="down-arrow">&#9660;</div>`{=html}
This had better be worth it.
`<div class="down-arrow">&#9660;</div>`{=html}
It's going to take ages to get back to the top.
`<div class="down-arrow">&#9660;</div>`{=html}
If only we had an easy way to get back...
`<div class="down-arrow">&#9660;</div>`{=html}
...that is both functional and fun.
`<div class="down-arrow">&#9660;</div>`{=html}
I call "back to top" buttons elevators...
`<div class="down-arrow">&#9660;</div>`{=html}
...they should really behave more like them.
`<div class="down-arrow">&#9660;</div>`{=html}
Ok, here we are... click that elevator!

{{< elevator audio=BossaBossa.mp3 >}}

Or `{{{< elevator "Return to 'Wow, all this scrolling.'" wow-all-this-scrolling audio=BossaBossa.mp3 >}}}` to scroll up to `## Wow, all this scrolling`.

:::

---

BossaBossa by Kevin MacLeod | <https://incompetech.com/>.  
Music promoted by <https://www.chosic.com/free-music/all/>.
Creative Commons Creative Commons: By Attribution 3.0 License (<http://creativecommons.org/licenses/by/3.0/>).
