#!/usr/bin/env bash
#
# Documentation Post-render Script
# Removes the transient files generated by pre-render.sh.
#
# @license MIT License
# @copyright 2026 Mickaël Canouil
# @author Mickaël Canouil
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOCS_DIR="$(dirname "${SCRIPT_DIR}")"

rm -f "${DOCS_DIR}/changelog.qmd" "${DOCS_DIR}/_variables.yml" "${DOCS_DIR}/ding.mp3"
printf '[post-render] Removed changelog.qmd, _variables.yml, and ding.mp3\n'
